/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-01 03:27:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addUserView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>회원가입</title>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/admin.css\" type=\"text/css\">\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("function fncAddUser() {\n");
      out.write("	// Form 유효성 검증\n");
      out.write("	var id=document.detailForm.userId.value;\n");
      out.write("	var pw=document.detailForm.password.value;\n");
      out.write("	var pw_confirm=document.detailForm.password2.value;\n");
      out.write("	var name=document.detailForm.userName.value;\n");
      out.write("	\n");
      out.write("	if(id == null || id.length <1){\n");
      out.write("		alert(\"아이디는 반드시 입력하셔야 합니다.\");\n");
      out.write("		return;\n");
      out.write("	}\n");
      out.write("	if(pw == null || pw.length <1){\n");
      out.write("		alert(\"패스워드는  반드시 입력하셔야 합니다.\");\n");
      out.write("		return;\n");
      out.write("	}\n");
      out.write("	if(pw_confirm == null || pw_confirm.length <1){\n");
      out.write("		alert(\"패스워드 확인은  반드시 입력하셔야 합니다.\");\n");
      out.write("		return;\n");
      out.write("	}\n");
      out.write("	if(name == null || name.length <1){\n");
      out.write("		alert(\"이름은  반드시 입력하셔야 합니다.\");\n");
      out.write("		return;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	if(document.detailForm.password.value != document.detailForm.password2.value) {\n");
      out.write("		alert(\"비밀번호 확인이 일치하지 않습니다.\");\n");
      out.write("		document.detailForm.password2.focus();\n");
      out.write("		return;\n");
      out.write("	}\n");
      out.write("		\n");
      out.write("	if(document.detailForm.phone2.value != \"\" && document.detailForm.phone2.value != \"\") {\n");
      out.write("		document.detailForm.phone.value = document.detailForm.phone1.value + \"-\" + document.detailForm.phone2.value + \"-\" + document.detailForm.phone3.value;\n");
      out.write("	} else {\n");
      out.write("		document.detailForm.phone.value = \"\";\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	/////////////////////////////////////////////////////////////////////////////////\n");
      out.write("	//document.detailForm.action='/addUser.do';\n");
      out.write("	/////////////////////////////////////////////////////////////////////////////////\n");
      out.write("	document.detailForm.action='/user/addUser';\n");
      out.write("	\n");
      out.write("	document.detailForm.submit();\n");
      out.write("	\n");
      out.write("}\n");
      out.write("\n");
      out.write("function check_email(frm) {\n");
      out.write("	alert\n");
      out.write("	var email=document.detailForm.email.value;\n");
      out.write("    if(email != \"\" && (email.indexOf('@') < 1 || email.indexOf('.') == -1)){\n");
      out.write("    	alert(\"이메일 형식이 아닙니다.\");\n");
      out.write("		return false;\n");
      out.write("    }\n");
      out.write("    return true;\n");
      out.write("}\n");
      out.write("\n");
      out.write("function checkSsn() {\n");
      out.write("	var ssn1, ssn2; \n");
      out.write("	var nByear, nTyear; \n");
      out.write("	var today; \n");
      out.write("\n");
      out.write("	ssn = document.detailForm.ssn.value;\n");
      out.write("	// 유효한 주민번호 형식인 경우만 나이 계산 진행, PortalJuminCheck 함수는 CommonScript.js 의 공통 주민번호 체크 함수임 \n");
      out.write("	if(!PortalJuminCheck(ssn)) {\n");
      out.write("		alert(\"잘못된 주민번호입니다.\");\n");
      out.write("		return false;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("function PortalJuminCheck(fieldValue){\n");
      out.write("    var pattern = /^([0-9]{6})-?([0-9]{7})$/; \n");
      out.write("	var num = fieldValue;\n");
      out.write("    if (!pattern.test(num)) return false; \n");
      out.write("    num = RegExp.$1 + RegExp.$2;\n");
      out.write("\n");
      out.write("	var sum = 0;\n");
      out.write("	var last = num.charCodeAt(12) - 0x30;\n");
      out.write("	var bases = \"234567892345\";\n");
      out.write("	for (var i=0; i<12; i++) {\n");
      out.write("		if (isNaN(num.substring(i,i+1))) return false;\n");
      out.write("		sum += (num.charCodeAt(i) - 0x30) * (bases.charCodeAt(i) - 0x30);\n");
      out.write("	}\n");
      out.write("	var mod = sum % 11;\n");
      out.write("	return ((11 - mod) % 10 == last) ? true : false;\n");
      out.write("}\n");
      out.write("\n");
      out.write("function fncCheckDuplication() {\n");
      out.write("	popWin \n");
      out.write("		= window.open(\"/user/checkDuplication.jsp\",\"popWin\", \"left=300,top=200,width=300,height=200,marginwidth=0,marginheight=0,scrollbars=no,scrolling=no,menubar=no,resizable=no\");\n");
      out.write("}\n");
      out.write("\n");
      out.write("function resetData() {\n");
      out.write("	document.detailForm.reset();\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body bgcolor=\"#ffffff\" text=\"#000000\">\n");
      out.write("\n");
      out.write("<form name=\"detailForm\"  method=\"post\" >\n");
      out.write("\n");
      out.write("<table width=\"100%\" height=\"37\" border=\"0\" cellpadding=\"0\"	cellspacing=\"0\">\n");
      out.write("	<tr>\n");
      out.write("		<td width=\"15\" height=\"37\">\n");
      out.write("			<img src=\"/images/ct_ttl_img01.gif\" width=\"15\" height=\"37\"/>\n");
      out.write("		</td>\n");
      out.write("		<td background=\"/images/ct_ttl_img02.gif\" width=\"100%\" style=\"padding-left:10px;\">\n");
      out.write("			<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("				<tr>\n");
      out.write("					<td width=\"93%\" class=\"ct_ttl01\">회원가입</td>\n");
      out.write("					<td width=\"20%\" align=\"right\">&nbsp;</td>\n");
      out.write("				</tr>\n");
      out.write("			</table>\n");
      out.write("		</td>\n");
      out.write("		<td width=\"12\" height=\"37\">\n");
      out.write("			<img src=\"/images/ct_ttl_img03.gif\" width=\"12\" height=\"37\"/>\n");
      out.write("		</td>\n");
      out.write("	</tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin-top:13px;\">\n");
      out.write("	\n");
      out.write("	<tr>\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\n");
      out.write("	</tr>\n");
      out.write("	\n");
      out.write("	<tr>\n");
      out.write("		<td width=\"104\" class=\"ct_write\">\n");
      out.write("			아이디 <img src=\"/images/ct_icon_red.gif\" width=\"3\" height=\"3\" align=\"absmiddle\"/>\n");
      out.write("		</td>\n");
      out.write("		<td bgcolor=\"D6D6D6\" width=\"1\"></td>\n");
      out.write("		<td class=\"ct_write01\">\n");
      out.write("			<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("				<tr>\n");
      out.write("					<td width=\"105\">\n");
      out.write("						<input 	type=\"text\" name=\"userId\" class=\"ct_input_bg\" \n");
      out.write("										style=\"width:100px; height:19px\"  maxLength=\"20\" >\n");
      out.write("					</td>\n");
      out.write("					<td>\n");
      out.write("						<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("							<tr>\n");
      out.write("								<td width=\"4\" height=\"21\">\n");
      out.write("									<img src=\"/images/ct_btng01.gif\" width=\"4\" height=\"21\"/>\n");
      out.write("								</td>\n");
      out.write("								<td align=\"center\" background=\"/images/ct_btng02.gif\" class=\"ct_btn\" style=\"padding-top:3px;\">\n");
      out.write("									<a href=\"javascript:fncCheckDuplication();\" id=\"btnCmfID\">ID중복확인</a>\n");
      out.write("								</td>\n");
      out.write("								<td width=\"4\" height=\"21\">\n");
      out.write("									<img src=\"/images/ct_btng03.gif\" width=\"4\" height=\"21\"/>\n");
      out.write("								</td>\n");
      out.write("							</tr>\n");
      out.write("						</table>\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("			</table>\n");
      out.write("		</td>\n");
      out.write("	</tr>\n");
      out.write("	\n");
      out.write("	<tr>\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\n");
      out.write("	</tr>\n");
      out.write("	\n");
      out.write("	<tr>\n");
      out.write("		<td width=\"104\" class=\"ct_write\">\n");
      out.write("			비밀번호 <img src=\"/images/ct_icon_red.gif\" width=\"3\" height=\"3\" align=\"absmiddle\"/>\n");
      out.write("		</td>\n");
      out.write("		<td bgcolor=\"D6D6D6\" width=\"1\"></td>\n");
      out.write("		<td class=\"ct_write01\">\n");
      out.write("			<input 	type=\"password\" name=\"password\" class=\"ct_input_g\" \n");
      out.write("							style=\"width:100px; height:19px\"  maxLength=\"10\" minLength=\"6\"  />\n");
      out.write("		</td>\n");
      out.write("	</tr>\n");
      out.write("	\n");
      out.write("	<tr>\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\n");
      out.write("	</tr>\n");
      out.write("	\n");
      out.write("	<tr>\n");
      out.write("		<td width=\"104\" class=\"ct_write\">\n");
      out.write("			비밀번호 확인 <img src=\"/images/ct_icon_red.gif\" width=\"3\" height=\"3\" align=\"absmiddle\"/>\n");
      out.write("		</td>\n");
      out.write("		<td bgcolor=\"D6D6D6\" width=\"1\"></td>\n");
      out.write("		<td class=\"ct_write01\">\n");
      out.write("			<input 	type=\"password\" name=\"password2\" class=\"ct_input_g\" \n");
      out.write("							style=\"width:100px; height:19px\"  maxLength=\"10\" minLength=\"6\"  />\n");
      out.write("		</td>\n");
      out.write("	</tr>\n");
      out.write("	\n");
      out.write("	<tr>\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\n");
      out.write("	</tr>\n");
      out.write("	\n");
      out.write("	<tr>\n");
      out.write("		<td width=\"104\" class=\"ct_write\">\n");
      out.write("			이름 <img src=\"/images/ct_icon_red.gif\" width=\"3\" height=\"3\" align=\"absmiddle\"/>\n");
      out.write("		</td>\n");
      out.write("		<td bgcolor=\"D6D6D6\" width=\"1\"></td>\n");
      out.write("		<td class=\"ct_write01\">\n");
      out.write("			<input 	type=\"text\" name=\"userName\" class=\"ct_input_g\" \n");
      out.write("							style=\"width:100px; height:19px\"  maxLength=\"50\" />\n");
      out.write("		</td>\n");
      out.write("	</tr>\n");
      out.write("	\n");
      out.write("	<tr>\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\n");
      out.write("	</tr>\n");
      out.write("	\n");
      out.write("	<tr>\n");
      out.write("		<td width=\"104\" class=\"ct_write\">주민번호</td>\n");
      out.write("		<td bgcolor=\"D6D6D6\" width=\"1\"></td>\n");
      out.write("		<td class=\"ct_write01\">\n");
      out.write("			<input 	type=\"text\" name=\"ssn\" class=\"ct_input_g\" style=\"width:100px; height:19px\" \n");
      out.write("							onChange=\"javascript:checkSsn();\"  maxLength=\"13\" />\n");
      out.write("			-제외, 13자리 입력\n");
      out.write("		</td>\n");
      out.write("	</tr>\n");
      out.write("\n");
      out.write("	<tr>\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\n");
      out.write("	</tr>\n");
      out.write("	\n");
      out.write("	<tr>\n");
      out.write("		<td width=\"104\" class=\"ct_write\">주소</td>\n");
      out.write("		<td bgcolor=\"D6D6D6\" width=\"1\"></td>\n");
      out.write("		<td class=\"ct_write01\">\n");
      out.write("			<input		type=\"text\" name=\"addr\" class=\"ct_input_g\" \n");
      out.write("						 	style=\"width:370px; height:19px\"  maxLength=\"100\"/>\n");
      out.write("		</td>\n");
      out.write("	</tr>\n");
      out.write("	\n");
      out.write("	<tr>\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\n");
      out.write("	</tr>\n");
      out.write("	\n");
      out.write("	<tr>\n");
      out.write("		<td width=\"104\" class=\"ct_write\">휴대전화번호</td>\n");
      out.write("		<td bgcolor=\"D6D6D6\" width=\"1\"></td>\n");
      out.write("		<td class=\"ct_write01\">\n");
      out.write("			<select 	name=\"phone1\" class=\"ct_input_g\" style=\"width:50px; height:25px\"\n");
      out.write("							onChange=\"document.detailForm.phone2.focus();\">\n");
      out.write("				<option value=\"010\" >010</option>\n");
      out.write("				<option value=\"011\" >011</option>\n");
      out.write("				<option value=\"016\" >016</option>\n");
      out.write("				<option value=\"018\" >018</option>\n");
      out.write("				<option value=\"019\" >019</option>\n");
      out.write("			</select>\n");
      out.write("			<input 	type=\"text\" name=\"phone2\" class=\"ct_input_g\" \n");
      out.write("							style=\"width:100px; height:19px\"  maxLength=\"9\" />\n");
      out.write("			- \n");
      out.write("			<input 	type=\"text\" name=\"phone3\" class=\"ct_input_g\" \n");
      out.write("							style=\"width:100px; height:19px\"  maxLength=\"9\" />\n");
      out.write("			<input type=\"hidden\" name=\"phone\" class=\"ct_input_g\"  />\n");
      out.write("		</td>\n");
      out.write("	</tr>\n");
      out.write("\n");
      out.write("	<tr>\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\n");
      out.write("	</tr>\n");
      out.write("	\n");
      out.write("	<tr>\n");
      out.write("		<td width=\"104\" class=\"ct_write\">이메일 </td>\n");
      out.write("		<td bgcolor=\"D6D6D6\" width=\"1\"></td>\n");
      out.write("		<td class=\"ct_write01\">\n");
      out.write("			<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("				<tr>\n");
      out.write("					<td height=\"26\">\n");
      out.write("						<input 	type=\"text\" name=\"email\" class=\"ct_input_g\" \n");
      out.write("										style=\"width:100px; height:19px\" onChange=\"check_email(this.form);\" />\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("			</table>\n");
      out.write("		</td>\n");
      out.write("	</tr>\n");
      out.write("\n");
      out.write("	<tr>\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\n");
      out.write("	</tr>\n");
      out.write("	\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"	style=\"margin-top:10px;\">\n");
      out.write("	<tr>\n");
      out.write("		<td width=\"53%\">	</td>\n");
      out.write("\n");
      out.write("		<td align=\"right\">\n");
      out.write("			<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("				<tr>\n");
      out.write("					<td width=\"17\" height=\"23\">\n");
      out.write("						<img src=\"/images/ct_btnbg01.gif\" width=\"17\" height=\"23\"/>\n");
      out.write("					</td>\n");
      out.write("					<td background=\"/images/ct_btnbg02.gif\" class=\"ct_btn01\" style=\"padding-top:3px;\">\n");
      out.write("						<a href=\"javascript:fncAddUser();\">가입</a>\n");
      out.write("					</td>\n");
      out.write("					<td width=\"14\" height=\"23\">\n");
      out.write("						<img src=\"/images/ct_btnbg03.gif\" width=\"14\" height=\"23\"/>\n");
      out.write("					</td>\n");
      out.write("					<td width=\"30\"></td>					\n");
      out.write("					<td width=\"17\" height=\"23\">\n");
      out.write("						<img src=\"/images/ct_btnbg01.gif\" width=\"17\" height=\"23\"/>\n");
      out.write("					</td>\n");
      out.write("					<td background=\"/images/ct_btnbg02.gif\" class=\"ct_btn01\" style=\"padding-top:3px;\">\n");
      out.write("						<a href=\"javascript:resetData();\">취소</a>\n");
      out.write("					</td>\n");
      out.write("					<td width=\"14\" height=\"23\">\n");
      out.write("						<img src=\"/images/ct_btnbg03.gif\" width=\"14\" height=\"23\"/>\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("			</table>\n");
      out.write("		</td>\n");
      out.write("	</tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
